#pragma once

enum ORTs
{
    ORT_ANONYMOUS = 0,
    ORT_CREATE_DELETE = 1,
    ORT_TIMER = 2,
    ORT_IO_RETAIN = 3,
    ORT_BUFFER_RETAIN = 4,
    ORT_IOCP_MESSAGE_RETAIN = 5,
    ORT_SIGHT_MESSAGE = 6,
    ORT_OBJECT_MAP = 7,
    ORT_OBJECT_NAME_MAP = 8,
    ORT_OBJECT_INDEX = 9,
    ORT_OBJECT_STORAGE = 10,
    ORT_FIND_OBJECT = 11,
    ORT_USER_DB = 12,
    ORT_TL_MAP = 13,
    ORT_SHARED_CONTAINER = 14,
    ORT_SMART_ID = 15,
    ORT_WORLD_COLLISION = 16,
    ORT_SERIALIZED_WORLD_THREAD = 17,
    ORT_NEIGHBOR_LIST = 18,
    ORT_GET_INVENTORY = 19,
    ORT_TEMP_USE = 20,
    ORT_CACHED = 21,
    ORT_WAREHOUSE_GET_WAREHOUSE = 22,
    ORT_USER_LOAD = 23,
    ORT_ACCOUNT_ADD_MAP = 24,
    ORT_FUNCTION_LOCAL = 25,
    ORT_FUNCTION_CHAIN = 26,
    ORT_EVENT_RETAIN = 27,
    ORT_INVENTORY_CHANGE_MAP = 28
};
