#pragma once

enum ServerToNpcPackets
{
    ServerToNpcPacket_VersionPacket = 0,
    ServerToNpcPacket_CreatePacket = 1,
    ServerToNpcPacket_EnterWorldPacket = 2,
    ServerToNpcPacket_MovePacket = 3,
    ServerToNpcPacket_SayPacket = 4,
    ServerToNpcPacket_AttackPacket = 5,
    ServerToNpcPacket_AttackedPacket = 6,
    ServerToNpcPacket_DiePacket = 7,
    ServerToNpcPacket_TalkPacket = 8,
    ServerToNpcPacket_TeleportRequestedEventPacket = 9,
    ServerToNpcPacket_BuyRequestedEventPacket = 10,
    ServerToNpcPacket_SellRequestedEventPacket = 11,
    ServerToNpcPacket_QuestAcceptedEventPacket = 12,
    ServerToNpcPacket_RequestNPCSpawn = 13,
    ServerToNpcPacket_MenuSelectEventPacket = 14,
    ServerToNpcPacket_ResurrectionPacket = 15,
    ServerToNpcPacket_SkillUsePacket = 16,
    ServerToNpcPacket_CheckMapIndex = 17,
    ServerToNpcPacket_MoveToPawn = 18,
    ServerToNpcPacket_QuestChoice = 19,
    ServerToNpcPacket_SeeCreature = 20,
    ServerToNpcPacket_SeeAttack = 21,
    ServerToNpcPacket_SeeSpell = 22,
    ServerToNpcPacket_OneSkillSelecte = 23,
    ServerToNpcPacket_LearnSkillRequest = 24,
    ServerToNpcPacket_SkillQuestAccept = 25,
    ServerToNpcPacket_SeeItem = 26,
    ServerToNpcPacket_ClassChangeRequest = 27,
    ServerToNpcPacket_FriendAttacked = 28,
    ServerToNpcPacket_TimePacket = 29,
    ServerToNpcPacket_DeleteNPCPacket = 30,
    ServerToNpcPacket_FinishUseSkill = 31,
    ServerToNpcPacket_TalkSelect = 32,
    ServerToNpcPacket_ClanAttack = 33,
    ServerToNpcPacket_SetAI = 34,
    ServerToNpcPacket_TimeHour = 35,
    ServerToNpcPacket_ClanSpelled = 36,
    ServerToNpcPacket_DesireManipuration = 37,
    ServerToNpcPacket_CreatePledge = 38,
    ServerToNpcPacket_DismissPledge = 39,
    ServerToNpcPacket_RevivePledge = 40,
    ServerToNpcPacket_LevelUpPledge = 41,
    ServerToNpcPacket_ServerPing = 42,
    ServerToNpcPacket_SiegeEvent = 43,
    ServerToNpcPacket_HolyThingSpelled = 44,
    ServerToNpcPacket_PongForCastleSiege = 45,
    ServerToNpcPacket_DeleteHatePacket = 46,
    ServerToNpcPacket_DeleteHateOfUserPacket = 47,
    ServerToNpcPacket_RandomizeHatePacket = 48,
    ServerToNpcPacket_ConfusePacket = 49,
    ServerToNpcPacket_RunAwayPacket = 50,
    ServerToNpcPacket_ContributionWinnerPledgePacket = 51,
    ServerToNpcPacket_GeneralEventPacket = 52,
    ServerToNpcPacket_UserObjectEvent = 53,
    ServerToNpcPacket_AgitEventPacket = 54,
    ServerToNpcPacket_TutorialMenuSelectEventPacket = 55,
    ServerToNpcPacket_TutorialQuestionMarkClicked = 56,
    ServerToNpcPacket_TutorialEvent = 57,
    ServerToNpcPacket_CreateAlliance = 58,
    ServerToNpcPacket_ManageCastleSiege = 59,
    ServerToNpcPacket_PetAction = 60,
    ServerToNpcPacket_RequestNPCInfo = 61,
    ServerToNpcPacket_DoorHpLevelInfo = 62,
    ServerToNpcPacket_ConrolTowerLevelInfo = 63,
    ServerToNpcPacket_NpcDoNothing = 64
};

#include <iosfwd>

std::ostream& operator<<(std::ostream& out, const ServerToNpcPackets packetId);  // FIXED: custom
